project:
  type: website
  output-dir: docs 

website:
  title: "AmruthaReddy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "hobbies"
        href: hobbies.qmd
      

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

